bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='shopping_bag'),
    path('add/<product_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<product_id>/', views.adjust_quantity,
         name='adjust_quantity'),
    path('remove/<product_id>/', views.delete_bag_item,
         name='delete_bag_item'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name="products"),
    path('<int:product_id>/', views.product_info, name='product_info'),
    path('product_review/<int:product_id>/', views.product_review,
         name='product_review'),
    path('update_review/<int:review_id>/', views.update_review,
         name='update_review'),
    path('delete_review/<int:review_id>/', views.delete_review,
         name='delete_review'),
    path('add_product', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product,
         name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product,
         name="delete_product"),

]

re_nu_apparel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('information/', include('information.urls')),
    path('reviews/', include('reviews.urls')),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 're_nu_apparel.views.handler404'

checkout/models.py
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.views import Product

from profiles.models import Profile
# Create your models here.


class Checkout(models.Model):
    # Order checkout model
    profile = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True,
                                related_name='user_orders')
    order_number = models.CharField(max_length=40, null=False, editable=False)
    date = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=40, null=False, blank=False)
    email = models.EmailField(max_length=80, null=False, blank=False)
    phone = models.IntegerField(null=False, blank=False)
    address_line_1 = models.CharField(max_length=100, null=False, blank=False)
    address_line_2 = models.CharField(max_length=100, null=True, blank=True)
    town = models.CharField(max_length=40, null=False, blank=False)
    city = models.CharField(max_length=40, null=False, blank=False)
    country = CountryField(blank_label="country", null=False, blank=False)
    postcode = models.CharField(max_length=40, null=False, blank=False)
    delivery = models.DecimalField(max_digits=8, decimal_places=2, null=False,
                                   default=0)
    total = models.DecimalField(max_digits=12, decimal_places=2, null=False,
                                default=0)
    grand_total = models.DecimalField(max_digits=12, decimal_places=2,
                                      null=False, default=0)

    def create_order_number(self):
        return uuid.uuid4().hex.upper()

    def update_total_cost(self):
        self.total = \
            self.ordernumber.aggregate(Sum('order_total'))['order_total__sum']
        if self.total < settings.FREE_DELIVERY:
            self.delivery_cost = self.total * settings.STANDARD_DELIVERY / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):

        if not self.order_number:
            self.order_number = self.create_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class Order_number(models.Model):
    # Order line model used for creating order
    order = models.ForeignKey(Checkout, null=False, blank=False,
                              on_delete=models.CASCADE,
                              related_name='ordernumber')
    product = models.ForeignKey(Product, null=False, blank=False,
                                on_delete=models.CASCADE)
    product_size = models.IntegerField(blank=True, null=True)
    qty = models.IntegerField(null=False, blank=False, default=0)
    order_total = models.DecimalField(max_digits=10, decimal_places=2,
                                      null=False, blank=False, editable=False)

    def save(self, *args, **kwargs):
        self.order_total = self.product.price * self.qty
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)
    category_name = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name

    def get_category_name(self):
        return self.category_name


class Product(models.Model):
    category = models.ForeignKey('Category', null=True, blank=True,
                                 on_delete=models.SET_NULL)
    name = models.CharField(max_length=200)
    sku = models.CharField(max_length=200)
    product_description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    rating = models.DecimalField(max_digits=5, decimal_places=2,
                                 null=True, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    image_url = models.URLField(max_length=1000, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product_review(models.Model):

    RATING = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    review = models.TextField()
    rating = models.IntegerField(choices=RATING)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

products/forms.py
from django import forms
from .models import Product_review, Product
from .widgets import CustomClearableFileInput


class productForm(forms.ModelForm):

    class Meta:
        model = Product_review
        fields = ('title', 'review', 'rating',)


class AdminProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

products/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse,\
     HttpResponseRedirect
from .models import Product, Category, Product_review
from django.db.models import Q
from django.db.models.functions import Lower
from django.contrib import messages
from .forms import productForm, AdminProductForm
from django.contrib import messages
from django.urls import reverse_lazy
# Create your views here.


def all_products(request):
    """products view """
    products = Product.objects.all()
    search_query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sorting = request.GET['sort']
            sort = sorting
            if sorting == 'name':
                sorting = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sorting == 'renu_category':
                sorting = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'descending':
                    sorting = f'-{sorting}'
            products = products.order_by(sorting)

    if request.GET:

        if 'renu_category' in request.GET:
            categories = request.GET['renu_category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

        if 's' in request.GET:
            search_query = request.GET['s']
            if not search_query:
                messages.error(request, 'please enter a search item')
                return redirect(reverse('products'))

            search_queries = Q(name__icontains=search_query) | Q(
                 product_description__icontains=search_query)
            products = products.filter(search_queries)

    current_sorting = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_queries': search_query,
        'active_category': categories,
        'current_sorting': current_sorting,
    }

    return render(request, 'products/products.html', context)


def product_info(request, product_id):
    """ Displays product info """
    product = get_object_or_404(Product, pk=product_id)
    product_reviews = Product_review.objects.filter(
        product_id=product.id)
    review_count = product_reviews.count()

    context = {
        'product': product,
        'product_reviews': product_reviews,
        'review_count': review_count,

    }

    return render(request, 'products/product_info.html', context)


def product_review(request, product_id):
    """ Displays product review """
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = productForm(request.POST)
        if form.is_valid():
            data = Product_review()
            data.title = form.cleaned_data['title']
            data.rating = form.cleaned_data['rating']
            data.review = form.cleaned_data['review']
            data.product_id = product_id
            data.user = request.user
            data.save()
            messages.success(
                request, 'Thanks, your review has been submitted.')
            return redirect(reverse('product_info', args=[product.id]))
        else:
            messages.error(
                request, "Sorry, your review could not be submitted.")
            return redirect(reverse('product_info', args=[product.id]))
    else:
        form = productForm()

    template = 'products/product_details.html'

    return render(request, template)


def delete_review(request, review_id):
    """ deletes user review """
    review = get_object_or_404(Product_review, pk=review_id)
    product = review.product

    if request.method == "POST":
        review.delete()
        messages.success(request, 'Your review has been successfully deleted')
        return redirect(reverse_lazy('product_info', args=[product.id]))

    return render(request, 'products/delete_review.html')


def update_review(request, review_id):
    """ updates the users review """
    all_reviews = get_object_or_404(Product_review, pk=review_id)
    product = all_reviews.product

    if request.method == "POST":
        form = productForm(request.POST, instance=all_reviews)
        if form.is_valid():
            form.save()
            messages.success(request, "Your review was updated")
            return redirect(reverse('product_info', args=[product.id]))
        else:
            messages.error(request, 'sorry, we cannot update your review')

    else:
        form = productForm(instance=all_reviews)

    template = 'products/update_review.html'
    context = {
        'form': form,
        'review': all_reviews,
        'product': product
     }
    return render(request, template, context)


def add_product(request):
    """ add product """
    if request.method == 'POST':
        form = AdminProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, f' Product has been successfully added')
            return redirect(reverse('product_info', args=[product.id]))

        else:
            messages.error
            (request, f' There was an error adding product, please try again')

    else:
        form = AdminProductForm()

        context = {
            'form': form,
        }

    return render(request, 'products/add_product.html', context)


def edit_product(request, product_id):
    """ edit product info"""
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = AdminProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            messages.success
            (request, f' product has been successfully updated')

            return redirect(reverse('product_info', args=[product.id]))

        else:
            messages.error(request, f' There was an error, please try again')

    else:
        form = AdminProductForm(instance=product)

        context = {
            'form': form,
            'product': product,
        }

    return render(request, 'products/edit_product.html', context)


def delete_product(request, product_id):
    """Delete product"""
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, f' The product was deleted')
    return redirect(reverse('products'))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}


{% block body %}
{% if user.is_superuser %}



<div class="col-12">
    <h2 class="text-center"> Add a product </h2>
    <form action="{% url 'add_product' %}" method="POST" class="add-product-form">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit" class="submit-btn mb-4 mt-4"> Add Product </button>
    </form>

    {% else %}
    <div class="pt-5">
        <h3 class="text-center"> Sorry you have no access </h3>
        <h5 class="text-center"> Only Store owners can access the product management page </h5>
    </div>
    <div>
        <h3 class="text-center"> <a href="{% url 'products'%}"> Go back shopping </a> </h3>
        <h3 class="text-center"><a href="{% url 'renu-go'%}"> Check out our next exclusive RENU GO events </a> </h3>
    </div>
    {% endif %}
</div>
{% endblock %}

products/templates/products/delete_review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Delete review
{% endblock %}

{% block body %}

<form method="post" class="mx-auto pt-5">
    {% csrf_token %}
    <p> You are about to delete your review </p>
    <input type="submit" value="Delete review" class="btn btn-danger btn-del pr-4 mr-2">
    <a href="{% url 'products' %}" class="btn submit-btn dlt-btn btn-cancel">Cancel</a>
</form>


{% endblock %}

products/templates/products/edit_product.html
{% extends "base.html" %}
{% load static %}


{% block body %}

<div class="col-12">
    <form action="{% url 'edit_product' product.id %}" method="POST">
        {% csrf_token %}
        {{ form|crispy}}
        <button type="submit"> Update </button>
    </form>
</div>
{% endblock %}

products/templates/products/edit_review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Products
{% endblock %}

{% block body %}
<div class="col-12">
    <form action="{% url 'update_review' review.id %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Update Review" class="btn submit-review">
        <a href="{% url 'product_details' product.id %}" class="btn rounded-0 btn-lg ">
            <span>
                <i class="fas fa-chevron-left"></i>
            </span>
            Back to Product
        </a>
    </form>
</div>
{% endblock %}

products/templates/products/product_info.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
Product Information
{% endblock %}


{% block body %}



<div class="fluid-container">

    <div class="row mt-5 ml-5 mr-5">

        <div class=" col-12 col-sm-4 col-md-6  mb-4 text-center">
            <div class="prod-info-image">

                <a href="{{ product.image.url }}" target="_blank">
                    {% if product.image %}
                    <img class="product-img" src="{{ product.image.url }}" alt="{{product.product}}">
                    {% else %}
                    <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="no image available">
                    {% endif %}
                </a>
            </div>
        </div>




        <div class=" col-12 col-md-6 col-lg-4">
            <div class="prod-info">
                <h3 class="text-left m-0 mt-3"> {{product.name}} </h3>
                <p class="text-left"> €{{product.price}}</p>
                {% if user.is_superuser %}
                <div class="admin-user">
                    <a href="{% url 'edit_product' product.id %}"> Edit product |</a>
                    <a href="{% url 'delete_product' product.id %}"> Delete product</a>
                    {% endif %}
                    <hr class="w-50 mb-4">
                    <p class="mt-2 mb-4"> {{product.product_description}}</p>

                    <form class="form" action="{% url 'add_to_bag' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% with product.has_sizes as p %}
                            {% if p %}
                            <div>
                                <select class="form-control" name="product_size" id="id_product_size">
                                    <option value="4"> Size 4 </option>
                                    <option value="6"> Size 6 </option>
                                    <option value="8"> Size 8 </option>
                                    <option value="10" selected> Size 10 </option>
                                    <option value="12"> Size 12 </option>
                                    <option value="14"> Size 14 </option>
                                    <option value="16"> Size 16 </option>
                                </select>
                            </div>
                            {% endif %}

                            <div class="col-12">
                                <p class="mt-3"><strong>Qty:</strong></p>
                                <div class="form-group w-50">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                            <button class="decrement-qty btn btn-black rounded-0"
                                                data-item_id="{{product.id}}" id="decrement-qty_{{product.id}}">
                                                <span class="icon">
                                                    <i class="fas fa-minus"></i>
                                                </span>
                                            </button>
                                        </div>
                                        <input class="form-control qty_input" type="number" name="qty" value="1" min="1"
                                            max="99" data-item_id="{{product.id}}" id="id_qty_{{product.id}}">
                                        <div class="input-group-append">
                                            <button class="increment-qty btn btn-black rounded-0"
                                                data-item_id="{{product.id}}" id="increment-qty_{{product.id}}">
                                                <span class="icon">
                                                    <i class="fas fa-plus"></i>
                                                </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="col-12">
                                <a href="{% url 'products' %}" class="btn btn-outline-black rounded-0 mt-3 ">
                                    <span class="icon">
                                        <i class="fas fa-chevron-left"></i>
                                    </span>
                                    Keep Shopping
                                </a>
                                <input type="submit" class="btn btn-black text-uppercase mt-3 submit-btn"
                                    value="Add to Bag">
                            </div>
                            <input type="hidden" name="redirect_url" value="{{ request.path }}">
                            {% endwith %}
                        </div>
                    </form>
                </div>

            </div>
        </div>
        <hr class="w-100">
        <div class="customer-review-container w-100 pl-3 pb-4 text-left">
            <h3 class="pb-4"> Customer Reviews ({{review_count}})</h3>
            {% for review in product_reviews %}
            <div>
                <p>{{ review.rating}} <i class="fa-solid fa-star"></i> <span class="text-muted "> {{ review.user }} on
                        {{ review.date }} </span></p>
                <strong> {{ review.review }}</strong>
                {% if request.user == review.user or request.user.is_superuser %}
                <a href="{% url 'delete_review' review.id %}"> <i class="delete fa-solid fa-trash-can"></i> </a>
                <a href="{% url 'update_review' review.id %}"><i class="modify fa-solid fa-pen-to-square"></i></a>
                {% endif %}
                <hr>
                {% endfor %}

            </div>

            {% if user.is_authenticated %}
            <div class="product-form-container w-100 pt-5">

                <form action="{% url 'product_review' product.id %}" class="product-review-form " method="POST">

                    {% csrf_token %}

                    <h4> Leave a Review </h4>
                    <div>
                        Review Title:
                        <input type="text" class="form-control" name="title" required>
                        <br>
                        Review:
                        <textarea name="review" class="form-control" rows="5" required></textarea>
                        <br>

                        <label for="rating"> Rating <i class="fa-solid fa-star"></i> </label>
                        <select name="rating" id="rating">
                            <option value="5">5</option>
                            <option value="4">4</option>
                            <option value="3">3</option>
                            <option value="2">2</option>
                            <option value="1">1</option>
                        </select>
                    </div>

                    <button type="submit" class="btn mt-2 mb-2 submit-btn"> Add Review </button>
                </form>
                {% else %}
                <p class="p-3"> Please <a href="{% url 'account_login'%}"> login </a> to leave a review <i
                        class="fa-regular fa-heart"></i></p>
                {% endif %}
            </div>
        </div>
    </div>
</div>




{% endblock %}

{% block js %}

{{ block.super }}
{% include 'products/includes/product_quantity.html'%}
{% endblock%}

products/templates/products/products.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Products
{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col text-center mt-3 mb-3 w-100 d-print-block">

            <h2> Products </h2>
            <h4>
                {% for c in active_category %}
                {{ c.get_category_name }}
                {% endfor %}
            </h4>

            <hr class="w-50 mb-1">
        </div>
    </div>
</div>

<div class="w-100 mb-3">
    <div class="dropdown-sort-products d-print-block w-20 float-right mr-5">
        <select id="sorting"
            class="custom-select custom-select-sm rounded-0 border border-{% if current_sorting != 'None_None' %}info{% else %}black{% endif %}">
            <option value="reset" disabled {% if current_sorting == 'None_None' %}selected{% endif %}>Sort products by
            </option>
            <option value="price_ascending" {% if current_sorting == 'price_ascending' %}selected{% endif %}>Price(low
                to high)</option>
            <option value="price_descending" {% if current_sorting == 'price_descending' %}selected{% endif %}>
                Price(high to low)</option>
            <option value="name_ascending" {% if current_sorting == 'name_ascending' %}selected{% endif %}> Name (A-Z)
            </option>
            <option value="name_descending" {% if current_sorting == 'name_descending' %}selected{% endif %}> Name (Z-A)
            </option>
        </select>
    </div>
</div>

<div class="row">


    <div class="col product-image text-center">

        <div class="row product-image-container">
            {% for product in products %}
            <div class="col-sm-6 col-md-6 col-lg-4 col-xl-3 mb-4 text-center">
                <div class="w-60">

                    <a href="{% url 'product_info' product.id %}">
                        {% if product.image %}
                        <img class="thumbnail thumbnail-image" src="{{ product.image.url }}" alt="{{product.product}}">
                        {% else %}
                        <img class="w-100" src="{{ MEDIA_URL }}noimage.png" alt="{{product.product}}">
                        {% endif %}
                    </a>
                    <h5 class="float-left mb-3 mt-1"> {{product.name}} </h5>
                    <p class=".d-print-inline-block float-right mt-1"> €{{product.price}}</p>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

</div>


<script type="text/javascript">
    $('#sorting').change(function () {
        var selector = $(this);
        var sorter = new URL(window.location);

        var selectOption = selector.val();
        if (selectOption != "reset") {
            var sort = selectOption.split("_")[0];
            var direction = selectOption.split("_")[1];

            sorter.searchParams.set("sort", sort);
            sorter.searchParams.set("direction", direction);

            window.location.replace(sorter);
        } else {
            sorter.searchParams.delete("sort");
            sorter.searchParams.delete("direction");

            window.location.replace(sorter);
        }

    });
</script>



{% endblock %}

products/templates/products/update_review.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Edit review
{% endblock %}

{% block body %}
<div class="col-12">
    <form action="{% url 'update_review' review.id %}" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <input type="submit" value="Update Review" class="btn submit-review">
        <a href="{% url 'product_info' product.id %}" class="btn rounded-0 btn-lg ">
            <span>
                <i class="fas fa-chevron-left"></i>
            </span>
            Back to Product
        </a>
    </form>
</div>
{% endblock %}